name: GitHub Readme YouTube Cards
on:
  workflow_dispatch:
  schedule:
    # Runs every day at 12:00 AM
    - cron: '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCvaovXZFgIzZLDnxa8RGQ4Q
          comment_tag_name: YOUTUBE-CARDS
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          show_duration: true
